"use strict";
exports.__esModule = true;
var BasicUser_1 = require("./Modelos/BasicUser");
var Admin_1 = require("./Modelos/Admin");
var miApp_1 = require("./Modelos/miApp");
var TextManager_1 = require("./Modelos/TextManager");
var miApp = new miApp_1["default"]();
var manager = new TextManager_1["default"]();
miApp.importUsers(manager.manageImport(manager.readFile('./Datos/users.txt')));
miApp.importAdmins(manager.manageImport(manager.readFile('./Datos/admins.txt')));
console.log(miApp.getUsersNames());
var admin1 = new Admin_1["default"]('Enrique', 'prueba@hola.com', '142387421', new Date(), 'prueba', 2);
var usuario1 = new BasicUser_1["default"]('Felipe', 'prueba@hola.com', '142387421', new Date(), 'hola', true);
var usuario2 = new BasicUser_1["default"]('Pepe', 'prueba@hola.com', '1423234', new Date(), 'hola2', false);
miApp.createUser(usuario1);
miApp.createUser(usuario2);
miApp.createAdmin(admin1);
console.log(miApp.getUsersNames());
usuario1.addPublication('Hola como estan?');
usuario1.addPublication('Holaaaa');
usuario1.addPublication('Publicacion 3');
usuario1.addPublication('Enrique el mejor admin');
console.log(usuario1.getPublications());
manager.saveFile('./Datos/users.txt', manager.manageExport(miApp.exportUsersForSave()));
manager.saveFile('./Datos/admins.txt', manager.manageExport(miApp.exportAdminsForSave()));
