console.log("Pasos para aprobar un examen:")
console.log("1. Prestar atencion al tema nuevo, si no vas a ser un choclo")
console.log("2. Tomar nota del tema, porque memoria de elefante no creo que tengas")
console.log("3. Leer el material del tema, no busques un resumen por internet")
console.log("5. Resolver los ejercicos, dale no creo que sean tan dificiles")
console.log("6. Preguntar al profesor todas tus dudas, dale que no muerde")
console.log("7. Armar un resumen para estudiar, graficos con flechitas y esas cosas")
console.log("8. Repasar resumen y ejercicios al menos una semana antes del examen, la noche anterior no dale media pila")
console.log("9. Tomar el examen sin machetes, que ya te conozco pillin")
console.log("10. Esperar a que el profesor lo corrija, ese señor tarda 20 años pero es lo que hay")
console.log("11. Aprobar :D (o no)")